# ---- Конфигурация для тестирования модели ----

# базовые гиперпараметры
batch_size: 16
num_workers: 4

# директории для тестовых датасетов
test_datasets:
  # casia1: "../datasets/CASIA1"
  # casia2: "../datasets/CASIA2_revised"
  # columbia: "../datasets/Columbia_final"
  
# для тестирования на части датасета
limit: 

# вывод подробной информации о процессе тестирования
verbose: True

# для тестирования только последней сохраненной модели, игнорируя пути к лучшим моделям
last: False
last_path: './checkpoints_models_rf/last.pth'

# пути к лучшим моделям для тестирования
hiding_net_path: "./checkpoints_models_rf/hiding_net_best.pth"
revealing_net_path: "./checkpoints_models_rf/revealing_net_best.pth"
